CREATE TABLE tweet (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_user int not null,
	tweet text not null,
	media_image text not null,
	media_video text not null,
	tgl text not null
)

--  Create View
select users.id as idUser, users.username as username, users.fullname as fullname, users.email as email, users.photoprofile as photoprofile, 
	tweet.id as idTweet, tweet.tweet as tweet, tweet.media_image as media_image, tweet.media_video as media_video, tweet.tgl as tgl	
	from users inner join tweet on users.id=tweet.id_user where users.id in (select id_user from follow where id_user = 1) or users.id in (select following from follow where id_user = 1)

CREATE OR REPLACE FUNCTION getHomeUser(idUsers int)
    RETURNS TABLE (
		iduser int,
        username text,
        fullname text,
        email text,
        bio text,
        photoprofile text,
        idtweet int,
		tweet text,
        media_image text,
        media_video text,
        tgl text
	)
    AS $$
    BEGIN
        RETURN QUERY select users.id as idUser, users.username as username, users.fullname as fullname, users.email as email, users.bio as bio, users.photoprofile as photoprofile, 
    	tweet.id as idTweet, tweet.tweet as tweet, tweet.media_image as media_image, tweet.media_video as media_video, tweet.tgl as tgl	
	    from users inner join tweet on users.id=tweet.id_user where users.id in (select id_user from follow where id_user = idUsers) or users.id in (select following from follow where id_user = idUsers) Order By tweet.id Desc;
    END; $$

    LANGUAGE 'plpgsql'

CREATE OR REPLACE FUNCTION getTweetUser(idUsers int)
RETURNS TABLE(
		iduser int,
        username text,
        fullname text,
        email text,
        photoprofile text,
        idtweet int,
		tweet text,
        media_image text,
        media_video text,
        tgl text
)
AS $$
BEGIN 
	RETURN QUERY select users.id as idUser, users.username as username, users.fullname as fullname, users.email as email, users.photoprofile as photoprofile, 
    	tweet.id as idTweet, tweet.tweet as tweet, tweet.media_image as media_image, tweet.media_video as media_video, tweet.tgl as tgl from users inner join tweet on users.id=tweet.id_user where users.id=idUsers;
END; $$

LANGUAGE 'plpgsql'
